version: '3'

services:

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto:/mosquitto/
    restart: unless-stopped

  influxdb:
    image: influxdb:2.0.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  influxdb:
  grafana-data:
